# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Charging_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(291, 109)
        self.label_select = QtWidgets.QLabel(Form)
        self.label_select.setGeometry(QtCore.QRect(20, 10, 271, 16))
        self.label_select.setObjectName("label_select")
        self.lineEdit_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_path.setGeometry(QtCore.QRect(20, 32, 251, 20))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.button_browse = QtWidgets.QPushButton(Form)
        self.button_browse.setGeometry(QtCore.QRect(20, 60, 121, 40))
        self.button_browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_browse.setObjectName("button_browse")
        self.button_get = QtWidgets.QPushButton(Form)
        self.button_get.setGeometry(QtCore.QRect(152, 60, 121, 40))
        self.button_get.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_get.setObjectName("button_get")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Charge Statistics"))
        self.label_select.setText(_translate("Form", "Select the planner folder to analyze:"))
        self.button_browse.setText(_translate("Form", "Browse"))
        self.button_get.setText(_translate("Form", "Get Stats"))
