# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delete_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(291, 139)
        self.label_select = QtWidgets.QLabel(Form)
        self.label_select.setGeometry(QtCore.QRect(20, 7, 271, 16))
        self.label_select.setObjectName("label_select")
        self.lineEdit_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_path.setGeometry(QtCore.QRect(20, 32, 251, 20))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.button_browse = QtWidgets.QPushButton(Form)
        self.button_browse.setGeometry(QtCore.QRect(30, 90, 111, 40))
        self.button_browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_browse.setObjectName("button_browse")
        self.button_delete = QtWidgets.QPushButton(Form)
        self.button_delete.setGeometry(QtCore.QRect(150, 90, 111, 40))
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_delete.setObjectName("button_delete")
        self.label_set = QtWidgets.QLabel(Form)
        self.label_set.setGeometry(QtCore.QRect(20, 60, 161, 20))
        self.label_set.setObjectName("label_set")
        self.lineEdit_days = QtWidgets.QLineEdit(Form)
        self.lineEdit_days.setGeometry(QtCore.QRect(160, 60, 71, 21))
        self.lineEdit_days.setObjectName("lineEdit_days")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Delete Files"))
        self.label_select.setText(_translate("Form", "Select a log folder to delete:"))
        self.button_browse.setText(_translate("Form", "Browse"))
        self.button_delete.setText(_translate("Form", "Delete"))
        self.label_set.setText(_translate("Form", "Set expire (days):"))
